# Generated by Django 5.2.4 on 2025-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_score', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-player_score', '-date'],
            },
        ),
    ]
