# Generated by Django 5.2.4 on 2025-08-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flagsgame', '0002_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_score', models.IntegerField()),
            ],
            options={
                'ordering': ['-player_score'],
            },
        ),
    ]
